### ISSUE TITLE
Yeoman generators 

### ISSUE THREAD

**Issue by ahmdrefat** [tailog/tailog-ui#5]

**Comment by ahmdrefat** [comment]
I think this is a good template https://github.com/kriasoft/react-starter-kit

**Comment by ikhattab** [comment]
+1
seems like a good one, I quickly checked others and I believe this'd be the best match for our case.

**Comment by NouranMahmoud** [comment]
+1 seems good

**Comment by ahmdrefat** [comment]
Okay.
